### ISSUE TITLE
Review English texts

### ISSUE THREAD

**Issue by saigkill** [saigkill/latex_curriculum_vitae-dotnet#3]
Sadly i'm a not native speaker in the english tongue. So it would be great, if anyone can review my english texts:

Documentation:
* Landing page: https://github.com/saigkill/latex_curriculum_vitae-dotnet/blob/master/docs/index.html
* The userdocs: https://github.com/saigkill/latex_curriculum_vitae-dotnet/tree/master/docssrc/xml
* English translation: https://github.com/saigkill/latex_curriculum_vitae-dotnet/blob/master/latex_curriculum_vitae/Properties/Resources.resx

**Comment by samanthahamilton** [comment]
Hi, @saigkill,

I'd be able to help review your English docs. Just to clarify, you're looking to address the:

- [ ] Index page
- [ ] Documentation pages
- [ ] Installation page (Chapter 2 of the documentation page)
- [ ] The 'application' wording

Do you need the README file tidied as well?

Cheers,
Sam

**Comment by saigkill** [comment]
Hi @samanthahamilton ,
thank you very much for helping out. 
You're right. That are the topics to translate. If you would like, you can also have a look on the Resources.resx file, what contains the english strings.
The README could also translated to "real" english. So if you want to fork, please base it on the 'develop' branch.

Greetings Sascha
