### ISSUE TITLE
Codereview

### ISSUE THREAD

**Issue by saigkill** [saigkill/latex_curriculum_vitae-dotnet#6]
I'm happy about codereviews. So i can learn how i can make things better :-)

**Comment by Fortuntato** [comment]
Do you mean like if there is any other way of achieving the same result with different code?

**Comment by saigkill** [comment]
Hi @Fortuntato ,
nice to read you. Yes that is mean't. If you have ideas to getting a better result, you are welcome :-)

**Comment by Fortuntato** [comment]
Ok, I am going to have a look at the whole project. I will first see if there is any bug I can find, then I can proceed at getting the code better

**Comment by saigkill** [comment]
Hi @Fortuntato ,
sound good. All help is welcome :-)
